package chat;

public enum MessageType {
    NAME_REQUEST,
    NAME_ACCEPTED,
    NAME_REJECTED,
    LIST_OF_USERS_REQUEST,
    LIST_OF_USERS_UPDATE,
    USER_ADDED,
    USER_REMOVED,
    USERNAME,
    ENTER_ROOM,
    EXIT_ROOM,
    TEXT,
    PRIVATE_TEXT,
    MY_OWN_PRIVATE_TEXT,
    PRIVATE_REQUEST,
    PRIVATE_ACCEPTED,
    PRIVATE_REJECTED,
    PRIVATE_CLOSED,
    LIST_OF_ROOMS_REQUEST,
    LIST_OF_ROOMS_UPDATE,
    NEW_ROOM_REQUEST,
    NEW_ROOM_ACCEPTED,
    NEW_ROOM_REJECTED

}
